### ISSUE TITLE
Summary - Meets Expectations

### ISSUE THREAD

**Issue by tbergen1** [kedarjoyner/jamming#12]
Overall, you did a great job with this project.  You demonstrated knowledge of the principles of React by knowing to avoid direct mutation of state within your methods.  You also leveraged ES6 syntax well and commented some of your code, which is great.  Your Spotify work was also great.  Awesome job.  Keep up the good work!

**Comment by kedarjoyner** [comment]
@tbergen1 Much appreciated for the review. Thank you!
