### ISSUE TITLE
Feature Request - Unable to Access Google Document

### ISSUE THREAD

**Issue by tbergen1** [kedarjoyner/jamming#13]
I couldn't access your Google Doc that contains your feature request.  I requested access, but you should make it open so anyone can see it.

**Comment by kedarjoyner** [comment]
@tbergen1 Thank you! I invited you to the document, but I also made it public. Sorry about that: https://docs.google.com/document/d/1BduFqFUn0vEmCI8KAJjIKkvBcqwE9an-VlfrKGsUC8Y/edit?usp=sharing
